language: node_js
node_js:
- '8'
env:
  global:
  - GH_USER_EMAIL="travis@example.org"
  - GH_USER_NAME="cozy-bot"
  - DEPLOY_REPOSITORY="git@github.com:konnectors/cozy-konnector-template.git"
  - secure: CQ44ZVjPAIVRvGgMcduSAX4VmaOrzF3nrJXPFUsNQ2tMVVdaAlI1zTNkdfntqigZgz6Mpk9x+2FcA8qrkNzQ4cW0lPP9f5dBtSH1xetfpXDFKprW4bqzmhgXSXJFTOYxkChOBPmCYJr+Vv4XqDkv/dBEPdfRSgvVyd5YxHSd5HBU91rKyR+Hox7LTnhmlXleLIs11EQgp7RK+L28MBCtCqAa2niFlKKRlqupm2FSpZzxCh9qeY0wKCQzPE+QZUm4waJ1SUGKQwbzAfyOxu2O6rwzaTSknfdJoSX6AMxjRTWBC9c3VfUGM3wjVJIqMhiUj2FQhVIjiDyX/W60/q3UMC5WYzSvEDDfhnKCPwiUKSU7HvSxx9q2YP34evxKo7KPahz9zLlQZvW+GBMyI9hbMDBTALuQVVzhftsvqfrogyYhkEPviiYiVADWNxhacsbUjRA5svXnZvtmCPo7fLFwel/krgC5Z8AwAY0YxWjSHNVScUkieSDCrlxrC09vTtG60unt9gtXbD5ruUkDLWSUwHBv2p0WY1TdP+2Vlf3yYfBvEVbqi59AxG+T17bq7Xv3QZnkrwC+UOCNCeg+gHPv+fRpUaYWzCO4uaoY/nlJa7RulQFhGca3A//6xRo/KgWw9JJnOXJelNjE9oHCUu9xShotUZKOF+O93V/BRqs9ITo=
  - secure: 3mqRKSme7y+M/tmCxQmwM8HiadtNpcmw7mE2ffuKD5FhHjKO5G8RrzF1rKyQADLiumhjSjJtZdo6x7858+TA29fl4hSTeqHhgqSRS3uXIzKXesL+8GVMxiQtk6z7Fo7jMQ7TicVgNUSPJsrLu1WfdcDerNwlOt/wBOEfcu2C7/4W971+YFgA/gO/DGsIeNockWKu+g3VuFOK+FYOL8i5KSF45Q0uPVZeJj188BeOmxztVzPDIceZTF5x9T0mYD33wpw77UHByxIN70pjFiNaFewwcGqzvoTJ0dh8Zd8Q8JAYUTxT+xqk/mgJP1U8rFgfAyrXoSf+bX6DzvWk5AhaBcETZc+lA0o8eYg+0TRgSW6fyaP1mR0EJJ2f29LpsqsmUmVLN1frU8gNWQfDgqeC88gGujSwxrbmDy2AUz/6Ail8ECYjxF8BBnKB6la/RHwBYT+MwGl9qn7hWKlAoge+atY2PXzYVgeRFKxHtvdje7crr0U6an1c0pop3CRGonN0TojnzmFWfAsVF7IH78NjTSdxWwdi0ALQzjioa0TvdVXbV/5FUxSYV6NNGGc40kBvDIjUY9pmmgyj0OH24EYm0tXNYSqfhXb+0R7QrQVC6HgjdEpJ9EnNFAiFxplDlU576/OSYnk4OeXLETgeOVmSj4J4lHjWcZNkXdPVty4NQJ8=
cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - build
  - latest
script:
- yarn lint
- yarn build
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    branch: master
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_b8447d6e3a47_key -iv $encrypted_b8447d6e3a47_iv
  -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/github_deploy_key
- ssh-add /tmp/github_deploy_key
